### ISSUE TITLE
First step in any frontend project!

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/FandomFusion-Frontend#1]
# Step 1

This issue focuses on designing the foundational UI/UX for the project. Your tasks include:

**Wireframe Creation**: Develop a comprehensive wireframe for all major screens, focusing on usability and design consistency.
**Color Theme & Typography**: Select a color palette and typography that aligns with the project's goals.
**Figma File**: Compile the design into a well-organized Figma file.
Requirements:

The design must be user-friendly, responsive, and scalable.
Adhere to modern UI/UX practices.
Follow a consistent structure to ensure seamless collaboration.

Basically you have to create a Figma file with all the required design requisites, like colour theme, wireframe, typography etc. An example figma file is attached in `Readme.md` file, kindly refer to that.

## Submission Guidelines:

- Upload the finalized Figma file link in your PR description.
- Document your design decisions (color theme, typography, layout principles) in the PR description.
- Use the [PR template](https://github.com/opencodeiiita/CubeSurfer/blob/main/.github/PULL_REQUEST_TEMPLATE.md) for submission.

> [!NOTE]
> The finalized figma file should also be uploaded in the *Figma* subsection of the `Readme.md`, nothing else should be changed.

## Resources:
- [Figma Basics]()
- [Modern Color Palettes](https://coolors.co/)
- [Google Fonts](https://fonts.google.com/)

## Point Submission
This is a **competitive** issue, meaning only the best will be merged and given points, so try to give your best and create an innovative and creative design y'all!

> Feel free to ask for clarification or guidance in the project's Discord channel. Good luck and happy designing! 🎨

Let me know if you'd like more details added or any adjustments! You can contact using the discord server, [join now](https://discord.gg/NxkSGu7M)

**Comment by Gamin8ing** [comment]
Guys, we just need to create a simple wireframe. Pick a color theme from **coolors.co** or **colorhunt**, choose a nice font, and decide on a basic layout. You can use some example from the given figma file in `Readme.md` or in the resources channel in the discord server.

**Comment by SHARUKA-2005** [comment]
claim

**Comment by Gamin8ing** [comment]
Hello @SHARUKA-2005 you can safely create a PR as this is an **competitve** issue, the best one before `4:30 pm` tommorrow will automatically be merged!

**Comment by Gamin8ing** [comment]
Congrats @rndastech 
This issue goes to you 🎉
