### ISSUE TITLE
Hello? 404 Not Found!

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/FandomFusion-Frontend#2]
# Design a Creative 404 Error Page  

**Description**:  
We need a **beautiful and creative 404 Error Page** for the project to ensure a polished user experience when users land on a non-existent route.  

**Your Task**:  
- Design a visually appealing 404 page with the following features:  
  1. **FandomFusion Title**: Display "FandomFusion" prominently at the top to match the branding.  
  2. **Error Message**: Include a friendly and creative message like:  
     - "Oops! You seem lost in the fandom universe."  
     - "404 - This page doesn't exist, but your journey doesn’t have to end here!"  
  3. **Call-to-Action Button**: Add a button to navigate back to the home page.  
     - Example text: "Take Me Home" or "Explore FandomFusion".  
  4. **Visuals**: Use an engaging illustration or animation (optional) to make the page more dynamic.  

- Create a React router to route non-existent page to the `404` page!

**Guidelines**:  
- The design should align with the **FandomFusion theme**.
- Ensure the page is **responsive**, so it looks great on all devices.  
- Save the component in `src/pages/404.jsx`.  
- Link it to the React Router to handle non-existent routes (e.g., `<Route path="*" element={<Error404 />} />`).  

**Resources**:  
- [Creative 404 Page Inspiration](https://dribbble.com/tags/404_page)  
- [React Router Documentation](https://reactrouter.com/en/main)  

**Submission**:  
1. Make all the changes, and be sure to pull all the changes before pushing all the changes!
2. Commit your changes and submit a PR using the `PR_template.md` avaible in the `.github` folder.
3. Add a screenshot or screen recording of your design in the PR description.  

> [!TIP]
> If you have any doubt please join the discord server and ask it right away!

Let’s make the fandom journey seamless and welcoming, even when users wander off the path! 🚀

**Comment by Rajvardhan222** [comment]
Claim

**Comment by apexcoder007** [comment]
claim

**Comment by Rajvardhan222** [comment]
Claim

**Comment by Gamin8ing** [comment]
@apexcoder007 issue is assigned to you 🎉
@Rajvardhan222 Please register on opencode and geekhaven portal first, then you may claim another issues!

cheers

**Comment by SHARUKA-2005** [comment]
Could You please assign it to me

**Comment by NityaB25** [comment]
claim

**Comment by Gamin8ing** [comment]
This issue is already assigned, check back later!

**Comment by rajdeep13-coder** [comment]
claim

**Comment by ayush-patel1** [comment]
claim

**Comment by Gamin8ing** [comment]
This issue is up for claiming @everyone

**Comment by Gamin8ing** [comment]
Congrats @Debankur04 issue is assigned to you 🎉

**Comment by official-ashutosh** [comment]
claim

**Comment by ayush-patel1** [comment]
claim
