### ISSUE TITLE
Ohh wait, leaving your footprints?

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/FandomFusion-Frontend#3]
# Add Your Name to the Contributors Page  

Yeah thats right, we shall save our memories here, right? what about leaving your footprints right here in this repo? Thats what we will be doing here.

**Description**:  
This is an **open-for-all** issue to help contributors get started with the project. Simply add your details to the **Contributors Page** and submit a PR!  

**Your Task**:  
1. Open the file located at `src/pages/Contributors.jsx`.  
2. Add a new entry for yourself in the contributors' list:  
   - **Name**: Your full name or GitHub username.  
   - **GitHub Profile Link**: Add a clickable link to your GitHub profile.  
   - **GitHub Avatar**: Display your GitHub profile picture using the provided template.  (right click your github profile picture and copy link address)

**Guidelines**:  
- Do not replace any data; add your entry alongside the existing ones, ensuring it is added below the previous entries.
- Follow the existing design structure for consistency.  
- Ensure your addition is neat and does not break the layout.  
- Submit a screenshot of your addition in the PR description.  

**Submission**:  
1. Make sure to pull any changes berforehand to avoid merge conflicts!
2. Commit your changes and submit a PR using the `PR_template.md` located in the `.github` folder.

> if you have any doubt, join the discord server!

Let’s showcase our contributors beautifully and collaboratively build FandomFusion! 🎉

**Comment by prince-yadav810** [comment]
i whould like to work on this

**Comment by Gamin8ing** [comment]
Thank you all!
