### ISSUE TITLE
UNO: Let the Cards Tell the Story!

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/FandomFusion-Frontend#36]
# Create a Versatile Card Component for Media Display  
**Deadline:** `18th December, 11:59:59 pm`

## **Description**:  
This is a **competitive** issue, worth 50 points, may the best one wins! We need a reusable **Card Component** to display movies, anime, and games across the project. This component should be dynamic, visually appealing, and follow the project's design theme as provided in the [**Figma file**](https://github.com/opencodeiiita/FandomFusion-Frontend?tab=readme-ov-file#figma). The card will include:  
- **Main Image**: Highlight the media visually.  
- **Title and Subtitle**: Provide essential details (e.g., name, categories).  
- **Add to Profile Button**: Allow users to interact with the media.  
- **Media-Specific Overlays**: Add dynamic overlays depending on the media type.  (given below)

---

## Inspiration

![image](https://github.com/user-attachments/assets/e6e6ff8f-a979-4e2a-a80c-295f093ac722)

![image](https://github.com/user-attachments/assets/f72d51b3-cf70-49be-b23a-510d5e45478d)

![image](https://github.com/user-attachments/assets/8086d826-a7fd-4e92-8e9e-0441167b142c)

![image](https://github.com/user-attachments/assets/2d29c424-eced-48ec-86e3-90077d937827)

![image](https://github.com/user-attachments/assets/7b7d4f44-a4f4-49c8-9f66-e6b0dc8d738d)

![image](https://github.com/user-attachments/assets/007906a3-35a4-4665-8932-299ba037ec88)

> [!NOTE]
> These are just solely for inspiration, I do not encourage you to copy them as it is, but take inspiration from.

---

**Your Task**:  

1. **Change the theme in TailwindCSS config file**:
    - Colour pallette has been referred in the [figma file in the `Readme.md` file, click here](https://github.com/opencodeiiita/FandomFusion-Frontend?tab=readme-ov-file#figma)
    - follow that colour pallette and update the tailwindCSS theme accordingly
    - refer [here](https://tailwindcss.com/docs/theme), official tailwindCss theme guide
    - also add the suitable font

2. **General Design Requirements**:  
   - Include the following elements:  
     - A **main image** that takes up most of the card.  
     - A **title** - name of the media
     - A **subtitle** (e.g., categories, release year).  
     - An **"Add to Profile" button** styled according to the theme.  
   - Add **hover animations** for interactivity (e.g., scale up, shadow effects) - go creative!

3. **Media-Specific Details**:  
   - **Games**:  
     - Display **platform logos** (e.g., PC, PlayStation, Xbox) at the top-right corner of the image.  
     - Overlay **star ratings** at the bottom-right corner of the image.  
   - **Movies**:  
     - Overlay the **IMDb rating** prominently at the bottom-right corner of the image.  
   - **Anime**:  
     - Display a **star rating** at the bottom-right corner of the image.  

4. **Reusable Code Practices**:  
   - Save the card component as `src/components/Card.jsx`.  
   - Sub-components (like images, buttons) should have their own files in `src/components`.  
   - Use props to dynamically populate content. Example:  
     ```jsx
     <Card
       type="movie"
       title="Inception"
       subtitle="Science Fiction"
       imageUrl="image-link"
       imdbRating={8.8}
       ...
     />
     ```  
   - Props should include:  
     - `type` (e.g., game, movie, anime).  
     - `title`, `subtitle`, `imageUrl`.  
     - Media-specific details like `platformLogos`, `imdbRating`, `starRating`, etc.

5. **Styling**:  
   - Use **TailwindCSS** for styling and ensure it aligns with the theme from the **Figma file**.  
   - Add **responsive design** so the cards look great on all devices.  

6. **Hover Animations**:  
   - Add subtle hover effects such as scaling, shadowing, or light transitions on the card and buttons for interactivity. 

> [!TIP]
> You can take inspiration from the Figma file, but the design is not limited to it. The most creative and styled one will be taken into consideration. 

---

**Submission Guidelines**:  
1. Save the component in the appropriate directory and follow the existing structure.  
2. Create a new branch named `add-card-component-<your-github-username>`.  
3. Submit a PR with the changes using the `PR_template.md` in the `.github` folder.
4. Include screenshots or videos of the card in action in the PR description.  

---

**Resources**:  
- [Best practices for card design](https://uxdesign.cc/8-best-practices-for-ui-card-design-898f45bb60cc)
- [TailwindCSS Documentation](https://tailwindcss.com/docs)
- [React Props Guide](https://reactjs.org/docs/components-and-props.html)
- [Figma File](https://github.com/opencodeiiita/FandomFusion-Frontend?tab=readme-ov-file#figma)
- [TailwindCSS guide on theme](https://tailwindcss.com/docs/theme)

Let’s make this component sleek and versatile for showcasing all our amazing media! 🚀

**Comment by ayush-patel1** [comment]
claim

**Comment by Gamin8ing** [comment]
> claim

No need to claim @ayush-patel1 it's a competitive issue, just raise a PR

**Comment by ayush-patel1** [comment]
ok @Gamin8ing

**Comment by Gamin8ing** [comment]
Thanks for participating in this issue, hope you have had fun!
