### ISSUE TITLE
FandomFusion’s Security Guards: Let's make them tough

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/FandomFusion-Frontend#60]
# Create Auth Pages for FandomFusio

## **Description**:  
This is a **competitive issue**, worth **50 points**, where you will design and implement a **signup screen**, a **login screen**, **reset password** and **forgot password** screens for FandomFusion. These pages are crucial for conveying the app's purpose and providing a seamless user experience.  

FandomFusion is a web app that connects fandoms from **movies**, **animes**, and **games**, all in one place. Users can:  
- Add their favorites from different media.  
- Suggest titles to friends.  
- Follow friends and see their current watch/play status.  
- Set statuses for partially completed movies, games, or animes.  

The design must have a **clean UI** and be responsive on both **mobile** and **desktop**, following the theme provided in the [**Figma file**](https://github.com/opencodeiiita/FandomFusion-Frontend?tab=readme-ov-file#figma).  

> [!TIP]
> You can take inspirations from various sites like `dribble`, `pinterest`, etc. These are just for inspiration, I am not suggestion any form of plaguerism.
---

## **Your Task**:  

1. **Creating auth pages with all the suitable links and fields described in following points.**

2. **Signup Screen**:  
   - Include fields for email, username, password, and confirm password.  
   - Add validation for each field (e.g., password length, valid email format).  
   - Provide clear error messages for invalid inputs.  

3. **Login Screen**:  
   - Include fields for email and password.  
   - Add a "Forgot Password?" link.  
   - Show error messages for invalid login attempts.  

4. **Forgot Password and Reset Password**:
   - Should include fields for email (Forgot password).
   - should include fields for new password and confirm new password (reset password).
   - Show feedback messages like email sent/OTP sent, password reset successfuly, some error occured, etc.

4. **General Design Requirements**:  
   - Follow the theme (colors, fonts) from the **Figma file**.  
   - Keep the UI intuitive and clean.  
   - Ensure responsiveness on mobile and desktop.  

6. **Reusable Code Practices**:  
   - Save components in appropriate directories (`src/pages` for screens, `src/components` for reusable elements like buttons or inputs).  
   - Reuse common components (e.g., a button component for "Signup" and "Login" buttons).  
   - Use TailwindCSS for styling.  

7. **Animations**:  
   - Add suitble animation and effects like hover effects to buttons and interactive elements to enhance user experience. 

> [!NOTE]
> Usage of `TailwindCSS` is recommended for css styling, and libraries like `framer motion` are allowed for adding effects and aniamations. 

---

## **Submission Guidelines**:  
1. Save the pages and components in the appropriate directories like:  
   - `src/pages/LandingPage.jsx`  
   - `src/pages/SignupPage.jsx`  
   - `src/pages/LoginPage.jsx` 
   - `...` 
2. Follow the existing folder structure and naming conventions.  
3. Create a new branch named `add-auth-pages-<your-github-username>`.  
4. Submit a pull request (PR) with your changes and make sure to **follow the damn...i mean, follow the `PR_template.md` from the `Readme.md` file**.  
6. Attach screenshots or screen recordings of the pages in your PR description.  

---

## **Resources**: 
- [TailwindCSS Documentation](https://tailwindcss.com/docs)  
- [Figma File](https://github.com/opencodeiiita/FandomFusion-Frontend?tab=readme-ov-file#figma)  
- [Formik for creating forms in react](https://formik.org/)  
- [Responsive Web Design](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design)  

Let’s make these pages shine and set the tone for FandomFusion! 🚀

**Comment by Gamin8ing** [comment]
congrats @Debankur04 this issue is assigned to you 🎉

**Comment by official-ashutosh** [comment]
Claim

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by PriyamJChakrabarty** [comment]
Claim
