### ISSUE TITLE
First Impressions Matter: Design FandomFusion’s Landing Page

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/FandomFusion-Frontend#64]
# Create a Beautiful Landing Page for FandomFusion  
**Points:** `30`  

---

## **Description**:  
This is a **first-come, first-serve (FCFS)** issue to design and implement the **Landing Page** for **FandomFusion**—the first page any user sees. The landing page should be visually appealing, responsive, and convey the purpose of the app effectively.  

---

### **What is FandomFusion?**  
FandomFusion is a web app that unites all fandoms from **movies**, **anime**, and **games** in one place. It allows users to:  
- Add their favorites from different media.  
- Suggest titles to friends.  
- Follow friends and explore what they’re currently watching or playing.  
- Set statuses for partially completed games, movies, or anime.  
- Share their love for fandoms through an interactive, clean, and user-friendly platform.  

---

### **Your Task**:  
1. **Design a Stunning Landing Page**:  
   - The page should include:  
     - **Features Section**: Highlight key features of FandomFusion (e.g., "Track Your Favorites," "Connect with Friends," "Discover New Titles").  
     - **About Us Section**: Provide a brief overview of FandomFusion and its purpose.  
     - **Contact Us Section**: Add a placeholder form with dummy data for now (e.g., Name, Email, Message fields).  
     - **Call-to-Actions (CTAs)**: Include buttons to navigate to the **Signup** and **Login** pages.  

2. **Add a Header**:  
   - Include a header at the top of the page with the following links:  
     - **Features**, **About Us**, and **Contact Us**.  
   - Link these header items to the respective sections on the page (use anchor links).  

3. **Animations and Effects**:  
   - Add subtle animations and effects to enhance the visual appeal of the page. Examples:  
     - Smooth scrolling for navigation.  
     - Hover effects on CTAs.  
     - Animations for section headings or images.  

4. **Styling and Responsiveness**:  
   - Use **TailwindCSS** for styling and ensure the design is responsive for both desktop and mobile devices.  

---

### **Guidelines**:  
1. Save the page in the `src/pages/LandingPage.jsx` file.  
2. Follow the theme (colors, fonts) provided in the [Figma file](https://github.com/opencodeiiita/FandomFusion-Frontend?tab=readme-ov-file#figma).  
3. Do not modify any other files or components in the repository.  

---

### **Submission Requirements**:  
1. Create a new branch named `add-landing-page-<your-github-username>`.  
2. Submit a pull request (PR) with the changes.  
3. Attach screenshots or a video showcasing the landing page in action in your PR description.  

---

### **Resources**:  
- [TailwindCSS Documentation](https://tailwindcss.com/docs)  
- [React Anchor Links for Navigation](https://www.npmjs.com/package/react-anchor-link-smooth-scroll)  
- [Responsive Web Design](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design)  
- [Figma File](https://github.com/opencodeiiita/FandomFusion-Frontend?tab=readme-ov-file#figma)  

---

Let’s make the first impression of FandomFusion unforgettable! 🚀

**Comment by Snehalgupta-07** [comment]
Claim

**Comment by Butterfly222-kartiki** [comment]
claim

**Comment by Gamin8ing** [comment]
congrats @Snehalgupta-07 this issue goes to you 🎉

**Comment by shrut2606** [comment]
claim
