### ISSUE TITLE
Where Fandoms Thrive: Design the Home Page

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/FandomFusion-Frontend#66]
# Build an Authorized Home Page for FandomFusion  
**Points:** `50`  

---

## **Description**:  
This is a **first-come, first-serve (FCFS)** major issue to design and implement the **Authorized Home Page** for **FandomFusion**. The home page is where users will land after signing in or signing up. The page should include all the core elements of a home feed and ensure a seamless user experience.  

---

### **What is FandomFusion?**  
FandomFusion is a web app that unites all fandoms from **movies**, **anime**, and **games** in one place. It allows users to:  
- Add their favorites from different media.  
- Suggest titles to friends.  
- Follow friends and explore what they’re currently watching or playing.  
- Set statuses for partially completed games, movies, or anime.  
- Share their love for fandoms through an interactive, clean, and user-friendly platform.  

---
### Inspiration
![image](https://github.com/user-attachments/assets/50a9a08a-d5cb-4727-9df8-d6cb82bc3638)
> this above image is from the **figma** file but doesn't include the left sidebar, so make sure to include that too.

![image](https://github.com/user-attachments/assets/d2951043-7046-4f74-9d38-c5bd190e79e6)

![image](https://github.com/user-attachments/assets/69d9b6b0-20c5-474b-8ecd-eda3abba620f)

### **Your Task**:  
1. **Authorization and Routing**:  
   - Implement a **protected route** for the home page.  
   - Redirect users to the **Landing Page** if they are not logged in.  
   - Show a **toast notification** (e.g., "Not Logged In") when redirecting unauthorized users.  

2. **Home Page Layout**:  
   - **Three Flows**:  
     - **Left Sidebar**:  
       - Links to the following pages: Home, Anime, Movies, Games, Profile.  
       - Add a **Logout** button at the bottom of the sidebar.  
       - Make the sidebar collapsible into a **hamburger menu** for mobile devices.  

     - **Middle Section (Main Feed)**:  
       - Display a **posts feed** with posts from the user’s friends or recommended content.  
       - Each post should include:  
         - Title.  
         - Media Type (Movie/Anime/Game).  
         - A short description or status.  
         - Interactions like "Like" and "Comment".  

     - **Right Sidebar**:  
       - Show **Friend Suggestions** (avatars and names).  
       - Display **Recommendations** from friends (e.g., movies, games, anime).  
       - the bottom bar to switch tabs from home to anime, movie, games. *(see inspiration mobile ideas)*

3. **Header and Footer**:  
   - Include placeholders for **Header** and **Footer** elements (if not created yet).  

4. **Styling and Responsiveness**:  
   - Use **TailwindCSS** for styling.  
   - Ensure the layout is fully responsive and works on mobile and desktop devices.  
   - Add hover effects, animations, and transitions for better user experience.  

5. **Reusability**:  
   - Break the layout into reusable components (e.g., Sidebar, Feed, FriendSuggestions).  
   - Save components in appropriate directories (`src/components`).  

---

### **Guidelines**:  
1. Ensure no other module or flow is broken by your implementation.  
2. Use any additional libraries/modules needed, but keep the project structure clean.  
3. Save the page in `src/pages/Home.jsx`.  
4. Use placeholder data for the posts, friend suggestions, and recommendations for now.  
5. Follow the existing directory structure and naming conventions.  

---

### Dummy data
Take the data or create a dummy data from `dummy_data.json` (create if not there). A json object will be there which will have `posts`, `animes`, etc.

### **Submission Requirements**:  
1. Create a new branch named `add-home-page-<your-github-username>`.  
2. Submit a pull request (PR) with your implementation.  
3. Attach screenshots or a video showcasing the home page layout and functionality.  **For both mobile and desktop views**.
4. Make sure to post the work to the discord channel to verify the correctness of the task.

---

### **Resources**:  
- [React Protected Routes](https://reactrouter.com/en/main/start/tutorial#adding-protected-routes)  
- [Toast Notifications with React-Toastify](https://fkhadra.github.io/react-toastify/introduction)  
- [TailwindCSS Documentation](https://tailwindcss.com/docs)  
- [Responsive Web Design](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design)  

---

Let’s create a dynamic and user-friendly home page that serves as the heart of FandomFusion! 🚀

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by Gamin8ing** [comment]
Congrats @PriyamJChakrabarty this issue goes to you 🎉 I hope you will have fun working with this one

**Comment by official-ashutosh** [comment]
Claim

**Comment by Gamin8ing** [comment]
@PriyamJChakrabarty also please collaborate with the assignee of issue #67 over the header and hamburger menu implementation,
thank you

**Comment by PriyamJChakrabarty** [comment]
Sure👍
