### ISSUE TITLE
Top It Off: Design the Perfect Header for FandomFusion

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/FandomFusion-Frontend#67]
### Create a Beautiful Header for FandomFusion  

**Points:** `30`  

---

## **Description**:  
This is a **first-come, first-serve (FCFS)** issue to design and implement the **Header** for **FandomFusion**. The header will serve as the navigation bar across the app, providing essential links and user actions.  

---

### **Your Task**:  
1. **Header Design**:  
   - Place the **app title** (e.g., "FandomFusion") prominently at the center of the header.  
   - Add a **hamburger menu** icon on the **left corner** for navigation (collapsible sidebar or navigation links) -> (**ONLY FOR MOBILE**).  
   - Include a **profile dropdown menu** on the **right corner**, with options for:  
     - **Profile**.  
     - **Logout** (ensure functionality is added for triggering logout).  

2. **Styling and Responsiveness**:  
   - Use **TailwindCSS** for styling and follow the theme provided in the [Figma file](https://github.com/opencodeiiita/FandomFusion-Frontend?tab=readme-ov-file#figma)  
   - Ensure the header is fully responsive for both mobile and desktop.  

3. **Reusability**:  
   - Save the header component in `src/components/Header.jsx`.  
   - Make it a reusable component that can be easily imported into other pages.  

4. **Integrations**:  
   - Include a placeholder for the hamburger menu functionality (will be implemented in another issue).  
   - Ensure the dropdown menu is interactive and functional.  

> [!Note]
> You have to communicate with the [`Issue #66`](https://github.com/opencodeiiita/FandomFusion-Frontend/issues/66) assignee to discuss the implementation of the hamburger menu.
---

### **Submission Requirements**:  
1. Create a new branch named `add-header-<your-github-username>`.  
2. Submit a pull request (PR) with your implementation.  
3. Attach screenshots or a video showcasing the header’s design and functionality in the PR description.  

---

### **Resources**:  
- [TailwindCSS Documentation](https://tailwindcss.com/docs)  
- [Dropdown Menu in React](https://www.w3schools.com/react/react_dropdowns.asp)
- [Responsive Navigation Bar](https://tailwindcss.com/docs/responsive-design)  

---

Let’s create a stunning and functional header for FandomFusion! 🚀

**Comment by Snehalgupta-07** [comment]
Claim

**Comment by official-ashutosh** [comment]
Claim

**Comment by Gamin8ing** [comment]
congrats @Snehalgupta-07 issue goes to you, hope you enjoy doin this one 🎉

**Comment by ayush-patel1** [comment]
claim

**Comment by Snehalgupta-07** [comment]
@Gamin8ing can u close this issue as it is still showing that it is assigned to me
