### ISSUE TITLE
Wrap It Up: Design the FandomFusion Footer

### ISSUE THREAD

**Issue by Gamin8ing** [opencodeiiita/FandomFusion-Frontend#68]
### Create a Beautiful Footer for FandomFusion  

**Points:** `30`  

---

## **Description**:  
This is a **first-come, first-serve (FCFS)** issue to design and implement the **Footer** for **FandomFusion**. The footer will provide links and contact options to enhance the user experience.  

---

### **Your Task**:  
1. **Footer Design**:  
   - Add links to the following pages:  
     - **Home Page**.  
     - **Landing Page**.  
     - **Contact Us Form** (placeholder for now).  
   - Include a copyright notice (e.g., "© 2024 FandomFusion").  

2. **Styling and Responsiveness**:  
   - Use **TailwindCSS** for styling and ensure the footer aligns with the theme in the [Figma file](https://github.com/opencodeiiita/FandomFusion-Frontend?tab=readme-ov-file#figma).  
   - Ensure the footer is responsive for all screen sizes.  

3. **Reusability**:  
   - Save the footer component in `src/components/Footer.jsx`.  
   - Make it a reusable component that can be easily imported into other pages.  

---

### **Submission Requirements**:  
1. Create a new branch named `add-footer-<your-github-username>`.  
2. Submit a pull request (PR) with your implementation.  
3. Attach screenshots or a video showcasing the footer’s design and functionality in the PR description.  

---

### **Resources**:  
- [TailwindCSS Documentation](https://tailwindcss.com/docs)
- [Creating Responsive Footers](https://tailwindcomponents.com/component/footer-3)  
- [React Footer Component Basics](https://www.freecodecamp.org/news/build-a-custom-footer-with-react/)

---

Let’s make the footer just as amazing as the header for FandomFusion! 🚀  
```

**Comment by official-ashutosh** [comment]
Claim

**Comment by Snehalgupta-07** [comment]
Caim

**Comment by Gamin8ing** [comment]
@official-ashutosh issue goes to you 🎉 
cheers

**Comment by ayush-patel1** [comment]
claim
